version: 2

jobs:
  macos:
    macos:
      xcode: "9.3"
    steps:
      - checkout
      - run: swift build
      - run: swift test


  linux:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        name: cleartext
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
      - image: scenecheck/postgres-ssl:latest
        name: tls
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test


  linux-release:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release

  linux-fluent:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - run:
          name: Clone Fluent PostgreSQL
          command: git clone -b gm https://github.com/vapor/fluent-postgresql.git
          working_directory: ~/
      - run:
          name: Switch Fluent PostgreSQL to this PostgreSQL revision
          command: swift package edit PostgreSQL --revision $CIRCLE_SHA1
          working_directory: ~/fluent-postgresql
      - run:
          name: Run Fluent PostgreSQL unit tests
          command: swift test
          working_directory: ~/fluent-postgresql

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-fluent
      - linux-release
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      # - macos
      
