#if !canImport(ObjectiveC)
import XCTest

extension ConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConnectionTests = [
        ("testBenchmark", testBenchmark),
        ("testClosureRetainCycle", testClosureRetainCycle),
        ("testDataDecoder", testDataDecoder),
        ("testEmptyArray", testEmptyArray),
        ("testGH125", testGH125),
        ("testGH141", testGH141),
        ("testGH24", testGH24),
        ("testGH46", testGH46),
        ("testInvalidDate", testInvalidDate),
        ("testListen", testListen),
        ("testNull", testNull),
        ("testNumericDecode", testNumericDecode),
        ("testOrderBy", testOrderBy),
        ("testPolygon", testPolygon),
        ("testRowCodableEmptyKeyed", testRowCodableEmptyKeyed),
        ("testRowCodableNested", testRowCodableNested),
        ("testRowCodableTypes", testRowCodableTypes),
        ("testRowDecoder", testRowDecoder),
        ("testSelectTypes", testSelectTypes),
        ("testStruct", testStruct),
        ("testSum", testSum),
        ("testTimeTz", testTimeTz),
        ("testURLParsing", testURLParsing),
        ("testVersion", testVersion),
        ("testZeroNumeric", testZeroNumeric),
    ]
}

extension PerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceTests = [
        ("testRangeSelectDecodePerformance", testRangeSelectDecodePerformance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConnectionTests.__allTests__ConnectionTests),
        testCase(PerformanceTests.__allTests__PerformanceTests),
    ]
}
#endif
