#if !canImport(ObjectiveC)
import XCTest

extension PostgresKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PostgresKitTests = [
        ("testCreateEnumWithBuilder", testCreateEnumWithBuilder),
        ("testPerformance", testPerformance),
        ("testSQLKitBenchmark", testSQLKitBenchmark),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PostgresKitTests.__allTests__PostgresKitTests),
    ]
}
#endif
