name: Update code coverage baselines
on:
  push: { branches: [ main ] }
jobs:
  update-main-codecov:
    strategy:
      matrix: { dbimage: ['postgres:14'], dbauth: ['scram-sha-256'] }
    runs-on: ubuntu-latest
    container: swift:5.6-focal
    env:
      LOG_LEVEL: debug
      POSTGRES_HOSTNAME: 'psql'
      POSTGRES_DB: 'test_database'
      POSTGRES_USER: 'test_username'
      POSTGRES_PASSWORD: 'test_password'
    services:
      psql:
        image: ${{ matrix.dbimage }}
        env:
          POSTGRES_USER: 'test_username'
          POSTGRES_DB: 'test_database'
          POSTGRES_PASSWORD: 'test_password'
          POSTGRES_HOST_AUTH_METHOD: ${{ matrix.dbauth }}
          POSTGRES_INITDB_ARGS: --auth-host=${{ matrix.dbauth }}
    steps:
      - name: Save Postgres version and method to env
        run: echo POSTGRES_INFO='${{ toJSON(matrix) }}' >> $GITHUB_ENV
      - name: Check out package
        uses: actions/checkout@v3
      - name: Run local tests with coverage
        run: swift test --enable-code-coverage
      - name: Submit coverage report to Codecov.io
        uses: vapor/swift-codecov-action@v0.2
        with:
          cc_flags: 'unittests'
          cc_env_vars: 'SWIFT_VERSION,SWIFT_PLATFORM,RUNNER_OS,RUNNER_ARCH,POSTGRES_INFO'
          cc_fail_ci_if_error: true
          cc_verbose: true
          cc_dry_run: false

